# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xy-T_esW4cMYFcnhFXtAfRBm4-H9ad9l
"""

!pip install streamlit yfinance pandas

import streamlit as st
import yfinance as yf
import pandas as pd

st.set_page_config(page_title="StockSense AI", layout="centered")

st.title("📈 StockSense AI")
st.subheader("AI-Powered Market Signal & Portfolio Assistant")

# -------- STOCK ANALYSIS --------
stock_name = st.text_input("Enter Stock (Example: TCS, RELIANCE, INFY)")

def analyze_stock(symbol):
    stock = yf.Ticker(symbol + ".NS")
    data = stock.history(period="1mo")

    if data.empty:
        return None, None, None, None

    latest_price = data['Close'].iloc[-1]
    avg_price = data['Close'].mean()

    # Simple signal logic
    if latest_price > avg_price:
        signal = "BUY 📈"
        reason = "Stock is trading above its average price indicating upward momentum."
    else:
        signal = "SELL 📉"
        reason = "Stock is trading below its average price indicating weakness."

    return latest_price, signal, reason, data

if stock_name:
    price, signal, reason, data = analyze_stock(stock_name)

    if price is None:
        st.error("Invalid stock. Try again.")
    else:
        st.write(f"### 💰 Price: ₹{round(price,2)}")
        st.write(f"### 📊 Signal: {signal}")
        st.write(f"### 🧠 Explanation: {reason}")
        st.line_chart(data['Close'])

# -------- PORTFOLIO ANALYSIS --------
st.markdown("---")
st.subheader("📁 Portfolio Analyzer")

portfolio = st.text_input("Enter stocks (comma separated): TCS,INFY,RELIANCE")

if portfolio:
    stocks = portfolio.split(",")
    results = []

    for s in stocks:
        s = s.strip()
        price, signal, _, _ = analyze_stock(s)
        if price:
            results.append({"Stock": s, "Price": price, "Signal": signal})

    if results:
        df = pd.DataFrame(results)
        st.dataframe(df)
    else:
        st.write("No valid stocks found.")

# -------- ABOUT --------
st.markdown("---")
st.write("Built for ET AI Hackathon 🚀")